# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: csdiff.spec

# add or remove files that should be synced
files_to_sync:
    - csdiff.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: csdiff
# downstream (Fedora) RPM package name
downstream_package_name: csdiff

release_suffix: ""
actions:
    post-upstream-clone: ./make-srpm.sh --generate-spec
    get-current-version: "sed -n 's|^Version: *||p' csdiff.spec"

jobs:
    - &copr
      job: copr_build
      trigger: pull_request
      metadata:
        targets:
            - epel-all-aarch64
            - epel-all-ppc64le
            - epel-all-s390x
            - epel-all-x86_64
            - fedora-all-aarch64
            - fedora-all-ppc64le
            - fedora-all-s390x
            - fedora-all-x86_64

    - <<: *copr
      trigger: commit
      metadata:
        owner: "@codescan"
        project: "csdiff"
        branch: main
