language: cpp
compiler: gcc

if: branch = main

matrix:
    include:
        - name: "Fedora Copr build"
          dist: focal
          env:
              - COPR_BUILD=yes

        - name: "Ubuntu LTS 2014 (trusty)"
          dist: trusty

        - name: "Ubuntu LTS 2016 (xenial)"
          dist: xenial

        - name: "Ubuntu LTS 2018 (bionic)"
          dist: bionic

        - name: "Ubuntu LTS 2020 (focal)"
          dist: focal

install:
    - sudo apt-get install cmake help2man libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-python-dev libboost-regex-dev

script:
    - if test -z "$COPR_BUILD"; then make distcheck; else ./.travis/copr-build ; fi
