#!/bin/sh
SELF="$0"

die(){
    echo "$SELF: error: $1" >&2
    exit 1
}

TOP="`dirname "$SELF"`"
CSGREP="`readlink -f "$TOP/csgrep"`"
test -x "$CSGREP" || die "csgrep not found"

set -x
"$CSGREP" --mode=json "$@" | sed -r 's|"([0-9])+",$|\1,|'
