#! /bin/bash -x

# Helper script to update CI scripting on Copr side

script=$(readlink -f "$(dirname "$0")")/copr-custom-script
script_resultdir=srpm_results
pkgname=csdiff

PROJECT_PR=@codescan/csdiff-pull-requests
PROJECT_PUSH=@codescan/csdiff

build_deps=(
    boost-devel
    bsdtar
    cmake
    coreutils
    gcc-c++
    git
    make
)

copr_cmd=(
    copr edit-package-custom \
    --webhook-rebuild on \
    --script "$script" \
    --script-chroot "fedora-latest-x86_64" \
    --script-builddeps "${build_deps[*]}" \
    --name "$pkgname" \
    --script-resultdir "$script_resultdir"
)

"${copr_cmd[@]}" "$PROJECT_PR" --max-builds 20
"${copr_cmd[@]}" "$PROJECT_PUSH"
