#! /bin/bash -x

# Helper script to update CI scripting on Copr side

script=$(readlink -f "$(dirname "$0")")/copr-custom-script

PROJECT_PR=@codescan/csdiff-pull-requests
PROJECT_PUSH=@codescan/csdiff

project=
case $1 in
    PR|'') project=$PROJECT_PR ;;
    PUSH) project=$PROJECT_PUSH ;;
esac

build_deps=(
    boost-devel
    boost-python3-devel
    bsdtar
    cmake
    coreutils
    gcc-c++
    git
    help2man
    make
    python3-devel
)

copr_cmd=(
    copr edit-package-custom "$project" \
        --webhook-rebuild on \
        --script "$script" \
        --script-chroot "fedora-latest-x86_64" \
        --script-builddeps "${build_deps[*]}"
)

if test "$1" != PUSH; then
    copr_cmd+=( --max-builds 10 )
fi


"${copr_cmd[@]}" --name csdiff --script-resultdir srpm_results
