#! /bin/bash -x

# Trigger the build in Copr (from .travis.yml)

set -e
curl -o copr-build https://raw.githubusercontent.com/praiskup/copr-ci-tooling/master/copr-travis-submit
export COPR_PR_WEBHOOK="https://copr.fedorainfracloud.org/webhooks/custom/46962/a72fe511-c141-4f27-b7cf-de03c065e64e/csdiff/"
exec bash copr-build
