---
name: Ubuntu CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  ubuntu:
    name: Ubuntu ${{ matrix.version }} (${{ matrix.compiler }})
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang++, g++]
        version: [18.04, 20.04, 22.04]

    runs-on: ubuntu-${{ matrix.version }}
    env:
      CXX: ${{ matrix.compiler }}
      CXXFLAGS: -Werror

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: '[clang] Install a default version for Ubuntu ${{ matrix.version }}'
        if: matrix.compiler == 'clang++'
        run: |
          sudo apt update
          sudo apt install -y clang

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y help2man libboost-dev libboost-filesystem-dev \
            libboost-program-options-dev libboost-python-dev libboost-regex-dev

      - name: Build and check
        run: |
          if [[ "${{ matrix.version }}" == 22.04 ]]; then
            # Make UBSAN print whole stack traces
            export UBSAN_OPTIONS="print_stacktrace=1"
            make distcheck-sanitizers
          else
            make distcheck
          fi
