---
name: RPM build in Fedora Copr
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Submit a Copr build
    runs-on: ubuntu-latest

    steps:
      - name: Check out proper version of sources
        uses: actions/checkout@v3

      - name: Submit the build
        env:
          COPR_PR_WEBHOOK: https://copr.fedorainfracloud.org/webhooks/custom/46962/a72fe511-c141-4f27-b7cf-de03c065e64e/csdiff/
          COPR_PUSH_WEBHOOK: ${{ secrets.COPR_PUSH_WEBHOOK }}
        run: |
          curl https://raw.githubusercontent.com/praiskup/copr-ci-tooling/main/copr-gh-actions-submit > submit
          bash submit ${{ github.event.pull_request.number }}
