---
name: Coverity

on:
  push:
    branches: [main]

jobs:
  coverity:
    name: Coverity Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y help2man libboost-dev libboost-filesystem-dev \
            libboost-program-options-dev libboost-python-dev libboost-regex-dev

      - name: Coverity scan
        uses: vapier/coverity-scan-action@v1
        with:
          email: ${{ secrets.COVERITY_SCAN_EMAIL }}
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
          project: csutils/csdiff
          command: make
